# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a2da801a90fc4db6541c3d997df9b70c0032be7333930a228f83bc4186f942b8732894174f661562b250399839704b0891fab749e54153b851683fcb98d44c

test:
  secret_key_base: 38644221f25bc3168db4cbdd98b354e11b94ae516522eeb0b4fc50b9ffb26af383f7a57d0811c655ff607a3795c5ee618bf5d30ce18ed01746cb61aec8152745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
